require("set")
require("remap")
require("telescope-config")
require("treesitter-config")
require("lsp-config")
require("cmp-config")
require("fidget-config")
require("colors")
vim.cmd('colorscheme nord')
